import type { AdCampaign } from "./ads";

export const MOCK_AD_CAMPAIGNS: AdCampaign[] = [
  {
    id: "ad_powerbi_2024",
    advertiserName: "DataAcademy",
    title: "Domine Power BI em 8 semanas",
    body: "Do básico ao avançado: dashboards profissionais, DAX e integração com Excel. Certificado reconhecido pelo mercado.",
    ctaLabel: "Ver curso grátis",
    targetUrl: "https://example.com/powerbi-course",
    category: "education",
    topicKeywords: ["dados", "análise", "excel", "relatório", "dashboard", "power bi", "bi", "business intelligence"],
    ageRating: "all",
    isActive: true,
  },
  {
    id: "ad_excel_2024",
    advertiserName: "PlanilhaPro",
    title: "Excel que o mercado exige",
    body: "Domine fórmulas avançadas, tabelas dinâmicas e automatize tarefas com macros. Mais de 50.000 alunos.",
    ctaLabel: "Começar grátis",
    targetUrl: "https://example.com/excel-pro",
    category: "education",
    topicKeywords: ["planilha", "excel", "dados", "trabalho", "organização", "tabela"],
    ageRating: "all",
    isActive: true,
  },
  {
    id: "ad_waterbottle_2024",
    advertiserName: "HidroLife",
    title: "Garrafa inteligente de 900ml",
    body: "Com marcador de consumo diário, tampa hermética e material livre de BPA. Hidrate-se com estilo.",
    ctaLabel: "Ver na loja",
    targetUrl: "https://example.com/hydro-bottle",
    category: "wellness",
    topicKeywords: ["água", "hidratação", "saúde", "exercício", "academia", "fitness"],
    ageRating: "all",
    isActive: true,
  },
  {
    id: "ad_planner_2024",
    advertiserName: "FocusFlow",
    title: "FocusFlow — planejador para mentes ocupadas",
    body: "Organize tarefas, metas e hábitos em um só lugar. Interface limpa, sem distração. Grátis para começar.",
    ctaLabel: "Testar grátis",
    targetUrl: "https://example.com/focusflow",
    category: "productivity",
    topicKeywords: ["organização", "produtividade", "tarefas", "metas", "hábitos", "planejamento", "agenda"],
    ageRating: "all",
    isActive: true,
  },
  {
    id: "ad_career_2024",
    advertiserName: "CareerBoost",
    title: "Prepare-se para entrevistas técnicas",
    body: "Simulados reais, feedback de especialistas e trilha personalizada para a sua área. Próxima entrevista = aprovado.",
    ctaLabel: "Ver trilhas",
    targetUrl: "https://example.com/career-boost",
    category: "career",
    topicKeywords: ["emprego", "carreira", "entrevista", "currículo", "trabalho", "vaga", "profissional"],
    ageRating: "all",
    isActive: true,
  },
];
