// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/beeyes-app/BeeEyes.tsx": () => import("../components/mockups/beeyes-app/BeeEyes.tsx"),
  "./components/mockups/beeyes-app/Mobile.tsx": () => import("../components/mockups/beeyes-app/Mobile.tsx"),
  "./components/mockups/beeyes-app/WebDesktop.tsx": () => import("../components/mockups/beeyes-app/WebDesktop.tsx")
};
