// ── Mock ad campaigns for development and testing ────────────────────────────
// Replace with real campaigns from backend or ad network in production.
// All campaigns have been reviewed to ensure they meet content policy requirements.

import type { AdCampaign } from "./ads";

const NOW = new Date().toISOString();
const FAR_FUTURE = "2027-12-31T23:59:59Z";

export const MOCK_ADS: AdCampaign[] = [
  {
    id: "bee_ad_001",
    title: "Aprenda Power BI do zero",
    description: "Crie dashboards profissionais e melhore seu currículo em semanas.",
    advertiserName: "DataMasters",
    callToActionText: "Ver curso",
    targetUrl: "https://example.com/powerbi",
    category: "education",
    tags: ["dados", "power bi", "carreira", "excel", "bi", "dashboard", "currículo"],
    isActive: true,
    startsAt: NOW,
    endsAt: FAR_FUTURE,
    ageRating: "all",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "bee_ad_002",
    title: "Excel avançado para sua carreira",
    description: "Domine fórmulas, dashboards e automações e se destaque no mercado.",
    advertiserName: "EduCareer",
    callToActionText: "Conhecer",
    targetUrl: "https://example.com/excel",
    category: "education",
    tags: ["excel", "carreira", "produtividade", "planilha", "automação", "dados"],
    isActive: true,
    startsAt: NOW,
    endsAt: FAR_FUTURE,
    ageRating: "all",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "bee_ad_003",
    title: "Lembre-se de beber água",
    description: "Uma garrafa prática para acompanhar sua hidratação e rotina de bem-estar.",
    advertiserName: "HydroShop",
    callToActionText: "Ver produto",
    targetUrl: "https://example.com/garrafa",
    category: "wellness",
    tags: ["saúde", "hidratação", "bem-estar", "rotina", "garrafa", "hábitos"],
    isActive: true,
    startsAt: NOW,
    endsAt: FAR_FUTURE,
    ageRating: "all",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "bee_ad_004",
    title: "Organize sua semana",
    description: "Planeje tarefas, estudos e hábitos em um só lugar.",
    advertiserName: "PlannerApp",
    callToActionText: "Ver ferramenta",
    targetUrl: "https://example.com/planner",
    category: "productivity",
    tags: ["organização", "produtividade", "hábitos", "tarefas", "planejamento", "agenda"],
    isActive: true,
    startsAt: NOW,
    endsAt: FAR_FUTURE,
    ageRating: "all",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "bee_ad_005",
    title: "Prepare-se para entrevistas",
    description: "Melhore seu currículo e treine respostas para recrutadores.",
    advertiserName: "CareerLab",
    callToActionText: "Ver dicas",
    targetUrl: "https://example.com/entrevistas",
    category: "career",
    tags: ["carreira", "entrevista", "currículo", "emprego", "vagas", "recrutamento"],
    isActive: true,
    startsAt: NOW,
    endsAt: FAR_FUTURE,
    ageRating: "all",
    createdAt: NOW,
    updatedAt: NOW,
  },
];
